#!/bin/sh
#  __                                  
# |  |--.-----.-----.--.--.--.--------.
# |  _  |__ --|  _  |  |  |  |        |
# |_____|_____|   __|________|__|__|__|
#             |__|  

# SETTINGS {{{
. "${HOME}/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d   "I" "II" "III" "IV" "V"

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.51
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config normal_border_color "$color1"
bspc config focused_border_color "$color5"
bspc config presel_feedback_color "$color5"
bspc config focus_follows_pointer true

# }}}

# AUTOSTART {{{

xset m 1 1 &
xscreensaver &
wal -R 
feh --bg-center ~/Pictures/Wallpapers/wallpaperlainfloat1.png
~/.config/polybar/launch.sh bspwm-bar &
picom --experimental-backend & # --shadow-color "$background" &
bsp-layout set tall 

# }}}

